common:
  app: opentripplanner-mcp
  shortname: otpmcp
  team: team-ror
  ingress:
    enabled: true
    trafficType: api
  service:
    internalPort: 8080
  deployment:
    prometheus:
      enabled: true
      path: "/actuator/prometheus"
      port: 9090
  container:
    env:
      - name: JDK_JAVA_OPTIONS
        value: "-server -Dspring.config.location=/etc/application-config/application.properties
        -Dfile.encoding=UTF-8 --add-opens java.base/java.lang=ALL-UNNAMED"
    image: <+artifacts.primary.image>
    cpu: 0.3
    memory: 512
    probes:
      readiness:
        path: "/readiness"
      liveness:
        path: "/liveness"
    volumeMounts:
      - mountPath: /etc/application-config
        name: application-config
        readOnly: true
    volumes:
      - configMap:
          defaultMode: 420
          name: opentripplanner-mcp
        name: application-config
  postgres:
    enabled: false