common:
  env: dev
  ingress:
    host: opentripplanner-mcp.dev.entur.io

configmap:
  urls:
    otp: https://api.dev.entur.io/journey-planner/v3/graphql
    geocoder: https://api.dev.entur.io/geocoder/v2/autocomplete