common:
  env: prd
  ingress:
    host: opentripplanner-mcp.entur.io

configmap:
  urls:
    otp: https://api.entur.io/journey-planner/v3/graphql
    geocoder: https://api.entur.io/geocoder/v2/autocomplete