common:
  env: tst
  ingress:
    host: opentripplanner-mcp.staging.entur.io

configmap:
  urls:
    otp: https://api.staging.entur.io/journey-planner/v3/graphql
    geocoder: https://api.staging.entur.io/geocoder/v2/autocomplete