common:
  app: otp-mcp-server
  shortname: otpmcp
  team: team-ror
  ingress:
    enabled: true
    trafficType: api
  service:
    internalPort: 8080
  deployment:
    prometheus:
      enabled: true
      path: "/actuator/prometheus"
  container:
    image: <+artifacts.primary.image>
    cpu: 0.3
    memory: 512
  postgres:
    enabled: false
